FROM python:3.9-slim

WORKDIR /streamlit

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/

ENTRYPOINT ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]